spring:
  application:
    name: devops-api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - ${DOMAIN_URL}
              - ${API_GATEWAY_URL}
              - ${API_GATEWAY_URL2}
              - ${API_GATEWAY_URL3}
              - ${API_GATEWAY_URL4}
              - ${API_GATEWAY_URL5}
              - ${API_GATEWAY_URL6}
              - ${API_GATEWAY_URL7}
              - ${API_GATEWAY_URL8}
              - ${API_GATEWAY_URL9}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: hello-route-non-auth
          uri: ${MAIN_ROUTE_ADDRESS}
          predicates:
            - Path=/hello/**
        - id: redis-route-non-auth
          uri: ${MAIN_ROUTE_ADDRESS}
          predicates:
            - Path=/redis/**

springdoc:
  swagger-ui:
#    path: ${SWAGGER_UI_PATH}
    urls[0]:
      name: devops-main
      url: ${MAIN_SWAGGER_PATH}