spring:
  application:
    name: devops-api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: # 모든 도메인 허용
              - ${DOMAIN_URL}
              - ${API_GATEWAY_URL2}
              - ${API_GATEWAY_URL4}
              - ${API_GATEWAY_URL5}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: hello-route-non-auth
          uri: ${MAIN_ROUTE_ADDRESS}
          predicates:
            - Path=/hello/**
        - id: redis-route-non-auth
          uri: ${MAIN_ROUTE_ADDRESS}
          predicates:
            - Path=/redis/**